name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install GHC
      env:
        CABAL_VERSION: 3.4.0.0
        GHC_VERSION: 8.10.5
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        ghcup install ghc ${GHC_VERSION}
        ghcup install cabal ${CABAL_VERSION}
        ghcup set ghc ${GHC_VERSION}
        ghcup set cabal ${CABAL_VERSION}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
